service: electric-chair-arena-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1

functions:
  getPlayers:
    handler: handler.getPlayers
    events:
      - http:
          path: players
          method: get
  getMatches:
    handler: handler.getMatches
    events:
      - http:
          path: matches
          method: get
  simulateMatch:
    handler: handler.simulateMatch
    events:
      - http:
          path: simulate
          method: post

plugins:
  - serverless-offline
  - serverless-dynamodb-local

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
