service: electric-chair-arena-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  environment:
    GEMINI_API: ${env:GEMINI_API, ''}

functions:
  getPlayers:
    handler: handler.getPlayers
    events:
      - http:
          path: get-players
          method: get
  startMatch:
    handler: handler.startMatch
    events:
      - http:
          path: start-match
          method: post
  getMatches:
    handler: handler.getMatches
    events:
      - http:
          path: get-matches
          method: get
  getMatchResult:
    handler: handler.getMatchResult
    events:
      - http:
          path: get-match-result
          method: get
  getLeaderboard:
    handler: handler.getLeaderboard
    events:
      - http:
          path: get-leaderboard
          method: get
  getAiMove:
    handler: handler.getAiMove
    events:
      - http:
          path: ai-move
          method: post
  saveMatch:
    handler: handler.saveMatch
    events:
      - http:
          path: save-match
          method: post
  generateCommentary:
    handler: handler.generateCommentary
    events:
      - http:
          path: generate-commentary
          method: post

plugins:
  - serverless-offline
  - serverless-dynamodb-local

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
